from __future__ import annotations

from housing_review.data.corpus import CHAPTER_URLS, RETRIEVED_ON, citation_contract_for_district
from housing_review.data.overlays import ADU_OVERLAY_LAYER
from housing_review.data.residential import CHAPTER_903_URL, ResidentialDistrictProfile, profile_residential_district
from housing_review.data.site import ZoningSiteContext
from housing_review.schemas.analyst import Claim
from housing_review.schemas.common import Typology

DIMENSIONS_SOURCE = (
    f"Chapter 903 §903.03 density table; {CHAPTER_URLS['903']}; retrieved {RETRIEVED_ON}"
)
CODE_GAPS = [
    "Whether a variance or special exception would actually be granted.",
    "Permitting timelines.",
    "Contextual setbacks or height alternatives under §925.06 / §925.07.",
]


def district_code_from_context(context: ZoningSiteContext) -> str | None:
    if context.districts:
        return context.districts[0].district_code
    return None


def deterministic_claims_for_typology(
    typology: Typology,
    *,
    district_code: str,
    profile: ResidentialDistrictProfile | None,
    adu_overlay: dict | None,
) -> list[Claim]:
    """Use-table, parking, and Chapter 903 facts. Citations are attached here, not by the LLM."""
    contract = citation_contract_for_district(district_code)
    row = contract[typology.value]
    claims = [
        Claim(
            statement=_use_statement(typology, row, district_code),
            basis="measured",
            source=row["use_source"],
        ),
        Claim(
            statement=_parking_statement(row),
            basis="measured",
            source=row["parking_citation"],
        ),
        Claim(
            statement=_dimensions_statement(profile, district_code),
            basis="measured",
            source=DIMENSIONS_SOURCE,
            confidence_note=(
                "Table values for this mapped density subdistrict. "
                "§925.06 / §925.07 alternatives are not applied here."
            ),
        ),
    ]
    if typology is Typology.adu:
        claims.append(_adu_overlay_claim(adu_overlay))
    return claims


def facts_pack_for_llm(
    context: ZoningSiteContext,
    typologies: list[Typology],
) -> list[dict]:
    """Slim structured facts the model may score from. Claims are not generated by the model."""
    district = district_code_from_context(context) or ""
    profile = context.residential_profile or profile_residential_district(district)
    contract = citation_contract_for_district(district) if district else {}
    overlay_layers = [hit.layer_id for hit in context.overlays]
    pack = []
    for typology in typologies:
        row = contract.get(typology.value) or {}
        pack.append(
            {
                "typology": typology.value,
                "title9_use": row.get("use_names") or [],
                "use_status": row.get("statuses") or [],
                "use_source": row.get("use_source"),
                "parking_minimum": row.get("parking_minimum"),
                "parking_maximum": row.get("parking_maximum") or None,
                "parking_source": row.get("parking_citation"),
                "dimensions": _dimensions_dict(profile, district),
                "dimensions_source": DIMENSIONS_SOURCE,
                "adu_overlay_query": context.adu_overlay,
                "overlay_layers_present": overlay_layers,
            }
        )
    return pack


def code_side_cannot_determine(profile: ResidentialDistrictProfile | None) -> list[str]:
    gaps = list(CODE_GAPS)
    if profile and profile.min_lot_sf is None:
        gaps.append("Minimum lot size is not listed in the §903.03.E Very-High Density table.")
    return gaps


def _use_statement(typology: Typology, row: dict, district_code: str) -> str:
    names = ", ".join(row.get("use_names") or [])
    statuses = "; ".join(row.get("statuses") or [])
    column = district_code.split("-", 1)[0]
    return (
        f"{names} in mapped district {district_code} (Use Table column {column}): {statuses}."
    )


def _parking_statement(row: dict) -> str:
    minimum = row.get("parking_minimum") or ""
    maximum = row.get("parking_maximum") or ""
    if maximum:
        return f"Off-street parking minimum {minimum}; maximum {maximum}."
    return f"Off-street parking: {minimum}."


def _dimensions_dict(profile: ResidentialDistrictProfile | None, district_code: str) -> dict:
    if not profile or not profile.standards:
        return {
            "district_code": district_code,
            "available": False,
            "note": "No Chapter 903 density profile for this mapped code.",
        }
    std = profile.standards
    return {
        "district_code": profile.district_code,
        "density_label": profile.density_label,
        "min_lot_sf": profile.min_lot_sf,
        "front_ft": std.get("front_ft"),
        "rear_ft": std.get("rear_ft"),
        "exterior_side_ft": std.get("exterior_side_ft"),
        "interior_side": std.get("interior_side"),
        "max_height": std.get("max_height"),
        "chapter_url": CHAPTER_URLS["903"],
        "section_url": CHAPTER_903_URL,
        "retrieved_on": RETRIEVED_ON,
    }


def _dimensions_statement(profile: ResidentialDistrictProfile | None, district_code: str) -> str:
    dims = _dimensions_dict(profile, district_code)
    if not dims.get("front_ft") and dims.get("available") is False:
        return f"No Chapter 903 dimensional table row for mapped district {district_code}."
    lot = dims.get("min_lot_sf")
    lot_txt = "no listed minimum lot size" if lot is None else f"minimum lot {lot} sf"
    return (
        f"{dims.get('district_code')} {dims.get('density_label')}: {lot_txt}; "
        f"front {dims.get('front_ft')} ft; rear {dims.get('rear_ft')} ft; "
        f"exterior side {dims.get('exterior_side_ft')} ft; interior side {dims.get('interior_side')}; "
        f"maximum height {dims.get('max_height')}."
    )


def _adu_overlay_claim(adu_overlay: dict | None) -> Claim:
    if adu_overlay is None:
        return Claim(
            statement="ADU Overlay membership was not queried for this site context.",
            basis="measured",
            source=ADU_OVERLAY_LAYER,
            confidence_note="Null overlay query is not a Yes/No map result.",
        )
    flag = adu_overlay.get("in_adu_overlay")
    return Claim(
        statement=(
            f"Live PGHWebZoningOverlays query for ADU / Accessory Dwelling labels: "
            f"in_adu_overlay={flag}."
        ),
        basis="measured",
        source=adu_overlay.get("layer_url") or ADU_OVERLAY_LAYER,
        confidence_note=adu_overlay.get("note"),
    )
